### ISSUE TITLE
Cannot set property writableObjectMode of #<Duplex> which has only a getter

### ISSUE THREAD

**Issue by Av32000** [hackergrrl/mic-stream#13]
Hello, when I run my script with this code (But I don't think the problem is with my code):
```
var mic = require('mic-stream')
const express = require("express")

app.get("/sound", (req, res) => {
    try {
      mic().pipe(res)
    } catch (error) {
      console.log(error)
    }
})
```
I get the following error:
```
/home/pi/prog/node_modules/audio-through/index.js:162
Through.prototype.writableObjectMode = true;
                                     ^

TypeError: Cannot set property writableObjectMode of #<Duplex> which has only a getter
    at Object.<anonymous> (/home/pi/prog/node_modules/audio-through/index.js:162:38)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/prog/node_modules/mic-stream/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
```

Am I the only one with this problem?

I am on an updated raspberrypi 4 with raspbian.
Thank you in advance

**Comment by hackergrrl** [comment]
I'm able to reproduce the crash -- it's not just you.

This module isn't maintained any longer. I recommend the [node-record-lpcm16](https://github.com/gillesdemey/node-record-lpcm16/) module!
